### ISSUE TITLE
Unable to use any other port apart from default ie 8125

### ISSUE THREAD

**Issue by akshaythakur1112** [kongo2002/kafka-statsd-reporter#1]
If you put any other port lets say XYZ in the below mentioned configuration, it will always try to use the default one. 

# StatsD server port (default: 8125)
external.kafka.statsd.metrics.port=XYZ

**Comment by kongo2002** [comment]
can you find the log messages (both on INFO level):

```
init: built config ...
```

```
configured to ...
```

**Comment by akshaythakur1112** [comment]
Yes, Its configuring to default port only. It is because of the following part of the code in the file **PropertiesMapBehavior.scala**

 
override def getInt(key: String, default: Int): Int = {
    map.get(key) match {
      case null => default
      case value: **Int => value**
      case _ => default
    }
  }


This should be replaced with 

 override def getInt(key: String, default: Int): Int = {
    map.get(key) match {
      case null => default
      case value: **String => value.toInt**
      case _ => default
    }
  }

As its getting key as string not int.

**Comment by kongo2002** [comment]
Thanks for investigating! 

Never occured to me that Kafka's configuration API is that 'weird'. However I will try to get a fix out soon.
